[project]
name = "website"
version = "1.0.0"
description = "Personal website made with Mkdocs Material and hosted on Cloudflare Pages"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.7.0",
]
